name: Build and Release WPF App

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      Solution_Name: ZCRTSPViewer_WPF.sln
      Configuration: Release

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build WPF project
      run: dotnet publish $env:Solution_Name --configuration $env:Configuration --output ./release --self-contained true --runtime win-x64

    - name: Package Release Files
      run: |
        mkdir packaged
        copy release\* packaged\
      shell: cmd

    - name: Upload to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: Release v1.0.${{ github.run_number }}
        draft: false
        prerelease: false
        files: packaged/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use a Personal Access Token (PAT) if repo is private
