name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    env:
      Solution_Name: ZCRTSPViewer_WPF.sln  # Your solution file
      Test_Project_Path: ZCRTSPViewer_WPF/ZCRTSPViewer_WPF/ZCRTSPViewer_WPF.csproj  # Path to test project

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET SDK
    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x  # Ensure this matches your project’s .NET version

    # Add MSBuild to the PATH
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore $env:Solution_Name

    # Build the solution
    - name: Build the application
      run: dotnet build $env:Solution_Name --configuration $env:Configuration --no-restore
      env:
        Configuration: ${{ matrix.configuration }}

    # Execute unit tests
    - name: Run unit tests
      run: dotnet test $env:Test_Project_Path --configuration $env:Configuration --no-build --verbosity normal
      env:
        Configuration: ${{ matrix.configuration }}

    # Decode the base64 PFX certificate (if signing is required)
    - name: Decode and store signing certificate
      if: env.Base64_Encoded_Pfx != ''
      run: |
        $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.Base64_Encoded_Pfx }}")
        $certificatePath = "$env:Temp\SigningCert.pfx"
        [System.IO.File]::WriteAllBytes($certificatePath, $pfx_cert_byte)
      shell: pwsh

    # Remove the PFX certificate after signing (for security)
    - name: Cleanup signing certificate
      if: env.Base64_Encoded_Pfx != ''
      run: Remove-Item -Path "$env:Temp\SigningCert.pfx"
      shell: pwsh

    # Upload build artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: BuildOutput
        path: ZCRTSPViewer_WPF/bin/${{ matrix.configuration }}/
